# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='full name')),
                ('phone', models.CharField(max_length=30, verbose_name='phone number')),
                ('email', models.CharField(max_length=120, verbose_name='email address')),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('emaildate', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
