# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 19:11
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=datetime.datetime(2016, 3, 18, 19, 11, 20, 83840, tzinfo=utc), editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
