# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160318_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('website', models.TextField()),
                ('comments', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.CharField(default=datetime.datetime(2016, 3, 19, 22, 42, 41, 306970, tzinfo=utc), max_length=5),
            preserve_default=False,
        ),
    ]
