# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 23:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160320_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dateposted',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 19, 23, 10, 47, 397590, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
